# This file contains values from Cookiecutter

default_context:
  project_name: "hezar-api"
  project_description: "Inference API Wrapper for hezar."
  organization: "rezashabrang"
  license: "MIT"
  minimal_python_version: 3.11
  github_name: "rezashabrang"
  email: "rezashabrang.m@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
