version: "3.7"

services:
  hezar-api:
    container_name: hezar-api
    image: hezar-api
    build:
      dockerfile: Dockerfile
      context: .
      # args:
      #   - http_proxy=http://10.0.11.10:8080
      #   - https_proxy=http://10.0.11.10:8080
    env_file:
      - .env
    ports:
      - 8080:80
    volumes:
      - .:/app/
    networks:
      - hezar-net

networks:
  hezar-net:
    name: hezar-net
